# Generated by Django 5.0.7 on 2026-03-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysessionlog',
            name='adherence_score',
            field=models.FloatField(default=0.0),
        ),
    ]
