# Generated by Django 5.0.7 on 2026-03-31 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_score', models.FloatField()),
                ('completion_rate', models.FloatField()),
                ('preferred_style', models.CharField(max_length=20)),
                ('strategies_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
