# Generated by Django 5.0.7 on 2026-05-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationlog',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
